### ISSUE TITLE
I'll just leave this test program here

### ISSUE THREAD

**Issue by rdebath** [ExtReMLapin/fast_brainfuck.lua#4]
https://github.com/rdebath/Brainfuck/blob/broken-and-trivial/bitwidth.b

**Comment by ExtReMLapin** [comment]
Thanks,

There is actually two bugs triggered by dead-ish code : 

The very first instruction loops while ptr isn't zero, but at the very start it's already zero.

And there was another error in the optimization pass where `[]` (dead code) existed.
